# Generated by Django 3.1 on 2020-08-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200824_1111'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
