# Generated by Django 3.1 on 2020-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200824_1111'),
        ('order', '0004_auto_20200824_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='excluded_ingredients',
            field=models.ManyToManyField(to='products.Ingredient'),
        ),
    ]
