# Generated by Django 3.1 on 2020-08-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_item_excluded_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='excluded_ingredients',
            new_name='ingredients',
        ),
    ]
